version: "0.1"

services:
  web:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
      POSTGRES_DB_PORT: 9999
      REDIS_DB_PORT: 9998
      REDIS_PASSWORD: 12345678
      PORT: 8080

  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '9999:5432'

  redis-db:
    image: redis:latest
    restart: always
    ports:
      - '9998:5432'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASES=16

  recipe:
    container_name: romel_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:${POSTGRES_DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
      - redis-db