server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: romel-auth-microservice
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:9999}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      port: ${REDIS_PORT:9998}
      password: ${REDIS_PASSWORD:12345678}
      host: ${REDIS_HOST:localhost}

jwt:
  key: DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY
  token-header: Authorization
  token-prefix: "Bearer "
  token-issuer: Romel

token-ttl:
  access: 3600
  refresh: 86400
