server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: romel-auth-microservice
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:postgres-postgresql:5432}/${POSTGRES_DB_NAME:patholody3d_pathology}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  main:
    allow-bean-definition-overriding: true

jwt:
  key: DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY_DEV-JWT-SIGN-KEY
  token-header: Authorization
  token-prefix: "Bearer "
  token-issuer: Romel
